variables:
  registry: gitlab.thevirtualbrain.org:5000
  tag: tvb/pycmdstan

build:
  stage: build
  script:
    - docker build -t $registry/$tag .

test:
  stage: test
  script:
    - docker run --rm $registry/$tag pytest --cov=pycmdstan -n 10 pycmdstan/tests.py

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $registry
    - docker push $registry/$tag

release_pypi:
  stage: deploy
  only:
    - tags
  script:
    - docker run --rm $registry/$tag python setup.py sdist bdist_wheel
    - docker run --rm $registry/$tag twine upload dist/*