variables:
  registry: gitlab.thevirtualbrain.org:5000
  tag: tvb/pycmdstan

build:
  stage: build
  script:
    - docker build -t $registry/$tag .

test:
  stage: test
  script:
    - docker run --rm $registry/$tag pytest --cov=pycmdstan --cov-report=term --cov-report=html -n 10 pycmdstan/tests.py
  artifacts:
    paths:
    - htmlcov/
    - "*.png"

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $registry
    - docker push $registry/$tag

release_pypi:
  stage: deploy
  only:
    - tags
  script:
    - docker run --rm $registry/$tag bash -c "python setup.py sdist bdist_wheel && twine upload -u $TWINE_USERNAME2 -p $TWINE_PASSWORD2 dist/*"