language: python

python:
  - "3.6"

cache:
  directories:
  - cmdstan-2.17.1

install:
  - pip install numpy
  - if [[ ! -d cmdstan-2.17.1 ]]; then curl -OL https://github.com/stan-dev/cmdstan/releases/download/v2.17.1/cmdstan-2.17.1.tar.gz && tar xzf cmdstan-2.17.1.tar.gz && rm -rf cmdstan-2.17.1.tar.gz && cd cmdstan-2.17.1 && make CC=g++ build; fi

script:
  - python -c 'print(42)'