language: python

python:
  - "3.6"

install:
  - pip install numpy
  - curl -OL https://github.com/stan-dev/cmdstan/releases/download/v2.17.1/cmdstan-2.17.1.tar.gz
  - tar xzf cmdstan-2.17.1.tar.gz
  - cd cmdstan* && make CC=g++ build

script:
  - python -c 'print(42)'